# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines
env:
  global:
    - CODACY_PROJECT_TOKEN=e03e55fa447b4f21811a99f63f7e9138

language: python

sudo: required

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

# See http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

before_install:
  - sudo apt-get update
  - pip install --upgrade pip setuptools

install:
  - pip install -r requirements.txt
  - pip install nose>=1.3.7 coverage codecov pytest>=3.0.5 codacy-coverage imageio matplotlib

before_script:
  - mkdir output

script:
  - nosetests -v --exe --with-doctest --with-xunit --with-coverage --cover-package=morphsnakes

after_success:
  - python setup.py install
  - codecov # PUBLIC project
  - coverage report && coverage xml
  - python-codacy-coverage -r coverage.xml
